### PR TITLE
refactor(analysis): rename to analysisById

### PR DESCRIPTION
**Pull request by maasencioh**
`¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by targos** [comment]
should we still merge this? @lpatiny ?

**Comment by maasencioh** [comment]
it's needed for a visualizer helper util

**Comment by targos** [comment]
ping @lpatiny

**Comment by lpatiny** [comment]
@maasencioh I don't remember why we did this view and can not find any call from visualizer-helper ... annoying. Do you remember anything more ?

**Comment by maasencioh** [comment]
@lpatiny is related with this view

https://github.com/cheminfo-js/visualizer-helper/blob/analysis/eln/analysis.js#L27

**Pull request closed without merging**
