### PR TITLE
feat: dates and owners searchable

### PR DESCRIPTION
**Pull request by kjappelbaum**
- trying to address https://github.com/cheminfo/eln.epfl.ch/issues/19
- hope is to be able to easily filter for creation/modification date ranges
- alternatively, we could seperately store year/month/day to make this searchable, but this approach seems to require less characters for the ususual usecase
- search for owners can be important if the initials are not consistently used in the sample names
- possibly addressing #2 (?)

### CODE REVIEW

**Comment by kjappelbaum** [comment]
@lpatiny i do not know if the formatting function is the most clever way to deal with the dates, but there is no native solution and YYYYMMDD seems the most convenient way to use the filter operators.

**Comment by lpatiny** [comment]
This project contains an example of toc but each installation has its own customised toc depending their application. This file on only used as demo on www.c6h6.org

**Comment by kjappelbaum** [comment]
ok, so you do not want to include such changes here and I should only make them in the relevant installations? Because this is also the default config used by the `roc-eln-docker`

**Comment by lpatiny** [comment]
Indeed you may tune the way you want the toc in your installation and we keep the default toc 'light'

**Pull request closed without merging**
